### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by formalizm**
Commits are arranged from more essential to less essential. If you don't like whitespace fixes, I could make a new PR without them.

The core of this PR is small, here is the main part (accounting for your last commit that mistakenly removed directory `6-color`):
[compare HEAD[-1] vs PR[-2]](https://github.com/spdegabrielle/flatt-languages/compare/master~...formalizm:flatt-languages:fixes~~), the rest is whitspace fixes.

### CODE REVIEW

**Comment by spdegabrielle** [comment]
Thank you for the PR 

This is a copy of the original code and it isn’t intended to be updated. 

Original code at https://cacm.acm.org/magazines/2012/1/144809-creating-languages-in-racket/fulltext

It looks like you did a good job. 

I’d  be happy to add a link to the readme of this repo with a link to your version - I wouldn’t want your work to go to waste.

best regards

Stephen

**Comment by formalizm** [comment]
Sure, no problem. Note, however, that this repository at the moment is missing `6-color` directory.

My reasoning to improve was that the article's code as-it-is is available already at ACM, hence, the GitHub version could get at least minor changes like fixing a bug that prevents running `2-modules` or whitespace fixes. I didn't consider those changes as 'real' updates.

A bigger issue that could get a real update is e.g. `6-color` seems to be broken for the current Racket distribution (apparently due to DrRacket API changes). But I didn't tackle that issue, anyways.

**Comment by spdegabrielle** [comment]
I didn’t realise thatt

**Comment by spdegabrielle** [comment]
Merged

will you try the bigger issue?

> A bigger issue that could get a real update is e.g. 6-color seems to be broken for the current Racket distribution (apparently due to DrRacket API changes). But I didn't tackle that issue, anyways.

**Comment by spdegabrielle** [comment]
I’ve added you as a collaborator

**Comment by formalizm** [comment]
Thank you.

By the way, for the code preservation purpose, we could fix a certain commit as an 'exactly identical to the original ACM code' by setting a branch or a tag as the 'original author's code. Exactly identical (having also a bug in `2-modules`) code is at the commit 76535cbe4929b72450317612b4fee26a27fc90e4.

For the `6-color` issue I will try to investigate in the coming month or so. What I understood by now that it 'works' in Racket 7.7, but not on Racket 8.8. However, I'm puzzled with its behaviour at the moment: even though it does not produce errors on DrRacket 7.7, the coloring (in normal or syntax-check modes) is exactly the same as on DrRacket 8.8 before `raco link`-ing the `6-color` language.

**Comment by spdegabrielle** [comment]
> By the way, for the code preservation purpose, we could fix a certain commit as an 'exactly identical to the original ACM code' by setting a branch or a tag as the 'original author's code. Exactly identical (having also a bug in 2-modules) code is at the commit https://github.com/spdegabrielle/flatt-languages/commit/76535cbe4929b72450317612b4fee26a27fc90e4.

that’s a great idea

> For the 6-color issue I will try to investigate in the coming month or so. 

thank you

It would be great if you could also share on the Racket [Discourse](https://racket.discourse.group/) and/or [Discord](https://discord.gg/6Zq8sH5) - as these are the most active places for Racket users and I’m sure others would be interested - and may have more insight to why it is failing in 8.8

thank you for your efforts

Stephen

**Pull request merged**
